### PR TITLE
Fix multi value issue

### LINKED ISSUE #1: Only works for single-value declarations
For example, the plugin will currently turn `padding: 15.24px 20.34px;` into `padding: 15px;`.

I think that this plugin could be made much more robust by using https://github.com/TrySound/postcss-value-parser. Are you open to a PR to try that out and add more tests?

### PR DESCRIPTION
**Pull request by himynameisdave**
Closes #1 where declarations with multiple values would become one value. Not ideal.

Special thanks to [`postcss-value-parser`](https://github.com/TrySound/postcss-value-parser) without which this would have been much more annoying.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,15 +1,23 @@
...
       css.walkDecls(function(decl){
-        //  any number of Numbers, a decimal, then 'px'
-        if( decl.value.match(/\d*?\.\d*?px/g) )
-          // those maths make it into a rounded Number,
-          // then we make it a string again by adding 'px'
-          decl.value = Math.round(parseFloat(decl.value)) + "px";
+        //  use the parser to walk through each individual value in the decl
+        decl.value = parser(decl.value).walk( function( node ){
+          //  we can totally skip things that aren't a pixel or "word" value
+          if( node.type === 'space' || node.type === 'function' || node.type === 'div' ){
```
Comment (davidtheclark) [inline index.js:10]: Any reason this couldn't be simplified into `if (node.type !== 'word') return;`?

File: index.js [hunk 2]
```diff
@@ -1,15 +1,23 @@
...
+            return false;
+          }
+          //  any number of Numbers, a decimal, then 'px'
+          if(node.value.match(/\d*?\.\d*?px/g) ){
```
Comment (davidtheclark) [inline index.js:14]: Any reason not to use https://github.com/TrySound/postcss-value-parser#valueparserunitvalue?

File: index.js (hunk 1 above)
Comment (himynameisdave) [inline index.js:10]: Yes you are totally right, and thanks for looking this over for me. :+1: So can you explain the difference between [the `word` and `string` types in the postcss-value-parser](https://github.com/TrySound/postcss-value-parser#node-types)?

Comment (davidtheclark) [inline index.js:10]: I believe the "string" type is for quoted strings, e.g. `content: "string in here";`. @TrySound is that right?

File: index.js (hunk 2 above)
Comment (himynameisdave) [inline index.js:14]: Ah very cool, I should definitely do a better job of :eyes: **reading over the documentation thoroughly** :eyes: before using something :stuck_out_tongue:

File: index.js (hunk 1 above)
Comment (TrySound) [inline index.js:10]: Yep. node.quote is wrapped around node.value on stringifying

File: index.js (hunk 2 above)
Comment (TrySound) [inline index.js:14]: @himynameisdave  If you have some misunderstanding you can ask me in issue and make a pr
